spring:
  application:
    name: itoken-service-redis
server:
  port: 6379
info:
  app.name: itoken-service-redis
  company.name: www.zhu.com
  buider.artifactId: $project.artifactId$
  builder.version: $project.version$