server:
  port: 8761
eureka:
  instance:
    hostname: 192.168.0.100
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://192.168.0.100:8762/eureka/
    #server:
    #enable-self-preservation: false 注销eureka的自我保护机制
spring:
  application:
    name: eurake
  zipkin:
    base-url: http://192.168.0.100:9411
  boot:
    admin:
      client:
        url: http://192.168.0.100:8084
