spring:
  application:
    name: itoken-service-sso
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: utf-8
    servlet:
      content-type: text/html

server:
  port: 9001
info:
  app.name: itoken-service-sso
  company.name: www.zhu.com
  buider.artifactId: $project.artifactId$
  builder.version: $project.version$