server:
  port: 9411
spring:
  application:
    name: zipkin
  boot:
    admin:
      client:
        url: http://localhost:9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: localhost
    prefer-ip-address: true
management:
  metrics:
    web:
      server:
        auto-time-requests: false