spring:
  zipkin:
    base-url: http://192.168.0.100:9411
  application:
    name: spring-cloud-admin
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health", "info"]


eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.100:8761/eureka/,http://192.168.0.100:8762/eureka/
server:
  port: 8084