server:
  port: 9411
spring:
  application:
    name: zipkin
  boot:
    admin:
      client:
        url: http://localhost:8084
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    instance-id: localhost
    prefer-ip-address: true
management:
  metrics:
    web:
      server:
        auto-time-requests: false