server:
  port: 8888
spring:
  application:
    name: itoken-config
  zipkin:
    base-url: http://192.168.0.100:9411
  boot:
    admin:
      client:
        url: http://192.168.0.100:8084
  cloud:
    config:
      server:
        git:
          uri: https://github.com/itokenteam/itoken-config.git   #github地址
          search-paths: respo
          username: happy_zhu@163.com
          password: zxm19930702
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.100:8761/eureka/,http://192.168.0.100:8762/eureka/,http://192.168.0.100:8763/eureka/
  instance:
    instance-id: cloud-config-8888
    prefer-ip-address: true
info:
  app.name: qianfeng
  company.name: www.zhu.com
  buider.artifactId: $project.artifactId$
  builder.version: $project.version$